### ISSUE TITLE
开发环境能否支持同时本地访问和远程网络访问

### ISSUE THREAD

**Issue by zerooneshang** [uba-templates/template-react-single-pages#3]
本地开发环境为localhost:3000或127.0.0.1:3000，create-react-app官方的可以同时localhost和ip访问，可否借鉴一下，方便其他人调试本地代码，谢谢

**Comment by kvkens** [comment]
设置IP：0.0.0.0 回环地址即可，是个不错的建议。

**Comment by kvkens** [comment]
最新版uba已经内置解决了该问题，我已在uba仓库回复你了。
